### ISSUE TITLE
FTDuino can not connect using WebUSB, Scratch nor Brickly

### ISSUE THREAD

**Issue by KKempen** [harbaum/ftduino#11]
Hi, just got the FTDuino in the mail and wrote the first few programs, now I wanted to use Scratch so I downloaded the IOServer software as described in the manual. 

On my Win10 machine when I try to connect using the online Scratch editor nothing shows up in the popup window;
![Screenshot](https://user-images.githubusercontent.com/59254242/71476108-ba9afb80-27e3-11ea-9f0e-f7ff1f4c3965.png)
When i do the same thing on my linux machine (Debian 10 Mate on a i386 architecture) usin' Chromium FTDuino shows up in de selection window, however when I try to connect. An error is returned: "Connection error: NotFoundError: The interface number provided is not supported by the device in its current configuration."
Can you please comment on this behaviour?

**Comment by harbaum** [comment]
Regarding the Windows issue: WebUSB can be rather tricky under Windows in general as seen e.g. here: https://github.com/WICG/webusb/issues/143

There are two "popular" ways to deal with this. Sometimes the following hint helps:

> Enabling new usb backend for Windows on Chrome flag solved the problem for us, chrome://flags/#new-usb-backend

And sometimes (more often) this one:

> Try to install WinUSB drivers manually with Zadig - https://zadig.akeo.ie/

**Comment by harbaum** [comment]
Regarding your Linux issue: I have never seen/heard that. The error message is not very detailed. Two things come to mind:

a) Is the correct sketch installed with the Board set to "ftduino (webusb)"?

b) The Udev rules have been setup correctly? Especially this one:
  ATTRS{idVendor}=="1c40" ATTRS{idProduct}=="0538", ENV{ID_MM_DEVICE_IGNORE}="1", MODE="0666"
