### ISSUE TITLE
Logo Proposal for ftDuino

### ISSUE THREAD

**Issue by area55git** [harbaum/ftduino#2]
Hello, I wish to cooperate with ftDuino, for this reason I have decided to design a logo for it. If you like this proposal, I can send you the files.

You can suggest the changes you think are necessary.

[![PROPUESTA_LOGO_FTDUINO.jpg](https://s18.postimg.cc/akfwjsgy1/PROPUESTA_LOGO_FTDUINO.jpg)](https://postimg.cc/image/cp09kvikl/)

**Comment by harbaum** [comment]
Thanks a lot for your contribution. These look really nice. We have used the old logo in many places now but i'll discuss your new logo with my coworkers.

**Comment by area55git** [comment]
It seems very good to me, if you accept my contribution you advise me to send you the logos in various formats.
