### ISSUE TITLE
Brickly demo

### ISSUE THREAD

**Issue by JoeTo1** [harbaum/ftduino#3]
Once that "Adafruit GFX Library" (https://github.com/adafruit/Adafruit-GFX-Library) is installed, the  sketch compiles fine.

FtduinoDisplay.h

Vielleicht könnte das in die Dokumentation aufgenommen werden.

**Comment by harbaum** [comment]
I might actually by default disable the usage of the display as 99% of all users won't use that.

**Comment by harbaum** [comment]
Hinweis zur Doku hinzugefügt. Wird im nächsten Release dabei sein.
